"""empty message

Revision ID: ec11fd95524e
Revises: 
Create Date: 2025-09-13 11:08:09.739749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec11fd95524e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('pfp', sa.String(length=200), nullable=True),
    sa.Column('is_artist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songname', sa.String(length=64), nullable=False),
    sa.Column('audiofile', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('fk_songs_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_songs_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('users')
    # ### end Alembic commands ###
